// src/components/Loader.tsx
import { motion, AnimatePresence } from 'framer-motion';
import { useEffect, useState } from 'react';

export default function Loader() {
  const [progress, setProgress] = useState(0);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // If CSS skip-loader is present, just stop loading logic immediately
    if (
      typeof document !== 'undefined' &&
      document.documentElement.classList.contains('skip-loader')
    ) {
      setIsLoading(false);
      return;
    }

    // Disable scroll while loading
    document.body.style.overflow = 'hidden';

    const duration = 1200; // 1.2s rapid counting
    const intervalTime = 20;
    const steps = duration / intervalTime;
    let currentStep = 0;

    const interval = setInterval(() => {
      currentStep++;
      const easeOutQuart = 1 - Math.pow(1 - currentStep / steps, 4);
      const nextProgress = Math.min(Math.round(easeOutQuart * 100), 100);
      setProgress(nextProgress);

      if (currentStep >= steps) {
        clearInterval(interval);
        setTimeout(() => {
          setIsLoading(false);
          document.body.style.overflow = '';
        }, 400); // Tiny pause at 100%
      }
    }, intervalTime);

    return () => {
      clearInterval(interval);
      document.body.style.overflow = '';
    };
  }, []);

  return (
    <AnimatePresence>
      {isLoading && (
        <motion.div
          key="loader"
          id="global-loader"
          initial={{ y: 0 }}
          exit={{ y: '-100%' }}
          transition={{ duration: 0.8, ease: [0.76, 0, 0.24, 1] }}
          className="bg-surface text-on-surface fixed inset-0 z-[100] flex flex-col justify-end p-6 md:p-12"
        >
          {/* Faint Architectural Grid Backdrop for loader */}
          <div
            className="pointer-events-none absolute inset-0 opacity-20 transition-opacity"
            style={{
              backgroundImage: `linear-gradient(to right, var(--color-on-surface-muted) 1px, transparent 1px), linear-gradient(to bottom, var(--color-on-surface-muted) 1px, transparent 1px)`,
              backgroundSize: '4rem 4rem',
            }}
          />

          <div className="relative z-10 flex w-full items-end justify-between">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
              className="text-xs tracking-[0.24em] text-[var(--color-on-surface-muted)] uppercase"
            >
              System Initialization
            </motion.div>
            <div className="font-display text-7xl leading-none tracking-tighter md:text-9xl">
              {progress}%
            </div>
          </div>

          <div className="relative z-10 mt-6 h-[1px] w-full overflow-hidden bg-[var(--color-surface-container-highest)]">
            <motion.div
              className="h-full bg-[var(--color-on-surface)]"
              style={{ width: `${progress}%` }}
              transition={{ duration: 0.1, ease: 'linear' }}
            />
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// src/components/chrome/Loader.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fly } from 'svelte/transition';
  import { cubicOut } from 'svelte/easing';

  let progress = $state(0);
  let isLoading = $state(true);
  let lineCount = $state(0);

  const bootLines = [
    'booting sheohn.os',
    'mounting modules … ok',
    'loading agent core … ok',
    'system ready',
  ];

  onMount(() => {
    if (
      typeof document !== 'undefined' &&
      document.documentElement.classList.contains('skip-loader')
    ) {
      isLoading = false;
      return;
    }

    document.body.style.overflow = 'hidden';

    const finish = () => {
      isLoading = false;
      document.body.style.overflow = '';
    };

    // Respect reduced motion: skip the boot animation, show the end state.
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      progress = 100;
      lineCount = bootLines.length;
      const t = setTimeout(finish, 200);
      return () => {
        clearTimeout(t);
        document.body.style.overflow = '';
      };
    }

    const duration = 800;
    const startTime = performance.now();
    let rafId: number;

    // Reveal boot-log lines one at a time as the bar fills.
    const lineId = setInterval(() => {
      if (lineCount < bootLines.length) lineCount += 1;
    }, 170);

    function tick(now: number) {
      const t = Math.min((now - startTime) / duration, 1);
      const easeOutQuart = 1 - Math.pow(1 - t, 4);
      progress = Math.min(Math.round(easeOutQuart * 100), 100);

      if (t < 1) {
        rafId = requestAnimationFrame(tick);
      } else {
        clearInterval(lineId);
        lineCount = bootLines.length;
        setTimeout(finish, 200);
      }
    }
    rafId = requestAnimationFrame(tick);

    return () => {
      cancelAnimationFrame(rafId);
      clearInterval(lineId);
      document.body.style.overflow = '';
    };
  });
</script>

{#if isLoading}
  <div
    id="global-loader"
    out:fly={{ y: '-100%', duration: 500, easing: cubicOut }}
    class="fixed inset-0 z-[200] flex flex-col justify-end bg-[var(--color-console-surface)] p-6 font-mono text-[var(--color-console-text)] md:p-12"
  >
    <!-- Faint architectural grid backdrop -->
    <div
      class="pointer-events-none absolute inset-0 opacity-[0.06]"
      style:background-image="linear-gradient(to right,
      var(--color-console-text) 1px, transparent 1px), linear-gradient(to
      bottom, var(--color-console-text) 1px, transparent 1px)"
      style:background-size="4rem 4rem"
    ></div>

    <div class="relative z-10">
      <!-- Boot log -->
      <div
        class="mb-8 space-y-1 text-xs text-[var(--color-console-text-dim)] sm:text-sm"
      >
        {#each bootLines.slice(0, lineCount) as line (line)}
          <div>
            <span class="text-[var(--color-console-signal)]">›</span>
            {line}
          </div>
        {/each}
      </div>

      <div class="flex w-full items-end justify-between">
        <div
          class="text-xs tracking-[0.24em] text-[var(--color-console-text-dim)] uppercase"
        >
          System Initialization
        </div>
        <div class="text-7xl leading-none tracking-tighter md:text-9xl">
          {progress}%
        </div>
      </div>

      <div class="mt-6 h-[2px] w-full overflow-hidden bg-white/10">
        <div
          class="h-full bg-[var(--color-console-signal)] transition-all duration-100 ease-linear"
          style:width="{progress}%"
        ></div>
      </div>
    </div>
  </div>
{/if}
