// src/components/CustomCursor.tsx
import { useEffect, useState } from 'react';
import { motion, useMotionValue } from 'framer-motion';

export default function CustomCursor() {
  const [isVisible, setIsVisible] = useState(false);
  const [isGreenHover, setIsGreenHover] = useState(false);

  // Use motion values for zero-latency tracking
  const mouseX = useMotionValue(-100);
  const mouseY = useMotionValue(-100);

  useEffect(() => {
    const updateMousePosition = (e: MouseEvent) => {
      mouseX.set(e.clientX);
      mouseY.set(e.clientY);
      setIsVisible(true);
    };

    const handleMouseOver = (e: MouseEvent) => {
      const target = e.target as HTMLElement;

      const isGreen =
        target.hasAttribute('data-cursor-green') ||
        target.closest('[data-cursor-green]');
      setIsGreenHover(!!isGreen);
    };

    const handleMouseLeave = () => setIsVisible(false);
    const handleMouseEnter = () => setIsVisible(true);

    window.addEventListener('mousemove', updateMousePosition, {
      passive: true,
    });
    window.addEventListener('mouseover', handleMouseOver);
    document.body.addEventListener('mouseleave', handleMouseLeave);
    document.body.addEventListener('mouseenter', handleMouseEnter);

    return () => {
      window.removeEventListener('mousemove', updateMousePosition);
      window.removeEventListener('mouseover', handleMouseOver);
      document.body.removeEventListener('mouseleave', handleMouseLeave);
      document.body.removeEventListener('mouseenter', handleMouseEnter);
    };
  }, [mouseX, mouseY]);

  return (
    <>
      <style>{`
        @media (pointer: fine) {
          *, body, a, button, input {
            cursor: none !important;
          }
        }
      `}</style>

      {/* Single solid instant cursor */}
      <motion.div
        className={`pointer-events-none fixed top-0 left-0 z-[9999] hidden rounded-full transition-colors duration-200 md:block ${isGreenHover ? 'bg-green-500 shadow-[0_0_15px_rgba(34,197,94,0.6)]' : 'bg-[var(--color-on-surface)] shadow-[0_2px_8px_rgba(0,0,0,0.15)]'}`}
        style={{
          x: mouseX,
          y: mouseY,
          translateX: '-50%',
          translateY: '-50%',
        }}
        animate={{
          width: 20,
          height: 20,
          opacity: isVisible ? 1 : 0,
        }}
        transition={{ duration: 0.15, ease: 'easeOut' }}
      />
    </>
  );
}

// src/components/CustomCursor.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';

  let isVisible = false;
  let isGreenHover = false;
  let mouseX = -100;
  let mouseY = -100;

  function updateMousePosition(e: MouseEvent) {
    mouseX = e.clientX;
    mouseY = e.clientY;
    isVisible = true;
  }

  function handleMouseOver(e: MouseEvent) {
    const target = e.target as HTMLElement;
    const isGreen =
      target.hasAttribute('data-cursor-green') ||
      target.closest('[data-cursor-green]');
    isGreenHover = !!isGreen;
  }

  function handleMouseLeave() {
    isVisible = false;
  }

  function handleMouseEnter() {
    isVisible = true;
  }

  onMount(() => {
    window.addEventListener('mousemove', updateMousePosition, { passive: true });
    window.addEventListener('mouseover', handleMouseOver);
    document.body.addEventListener('mouseleave', handleMouseLeave);
    document.body.addEventListener('mouseenter', handleMouseEnter);
  });

  onDestroy(() => {
    if (typeof window !== 'undefined') {
      window.removeEventListener('mousemove', updateMousePosition);
      window.removeEventListener('mouseover', handleMouseOver);
      document.body.removeEventListener('mouseleave', handleMouseLeave);
      document.body.removeEventListener('mouseenter', handleMouseEnter);
    }
  });
</script>

<style>
  @media (pointer: fine) {
    :global(*), :global(body), :global(a), :global(button), :global(input) {
      cursor: none !important;
    }
  }
</style>

<!-- Single solid instant cursor -->
<div
  class="pointer-events-none fixed top-0 left-0 z-[9999] hidden rounded-full transition-colors duration-200 md:block {isGreenHover ? 'bg-green-500 shadow-[0_0_15px_rgba(34,197,94,0.6)]' : 'bg-[var(--color-on-surface)] shadow-[0_2px_8px_rgba(0,0,0,0.15)]'}"
  style:transform="translate({mouseX}px, {mouseY}px) translate(-50%, -50%)"
  style:width="20px"
  style:height="20px"
  style:opacity={isVisible ? 1 : 0}
  style:transition="opacity 0.15s ease-out, background-color 0.2s, box-shadow 0.2s"
></div>
