// src/components/HeroSection.tsx
import {
  motion,
  useScroll,
  useSpring,
  useTransform,
  type Variants,
} from 'framer-motion';
import { useRef } from 'react';
import DecoderText from './DecoderText';

const containerVariants: Variants = {
  hidden: { opacity: 0, y: 18 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.7,
      ease: [0.22, 1, 0.36, 1],
      staggerChildren: 0.12,
    },
  },
};

const itemVariants: Variants = {
  hidden: { opacity: 0, y: 12 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
};

export default function HeroSection() {
  const sectionRef = useRef<HTMLElement | null>(null);
  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ['start start', 'end start'],
  });

  // Gentle parallax for a "glide" feel while scrolling.
  const parallaxY = useSpring(useTransform(scrollYProgress, [0, 1], [0, -40]), {
    stiffness: 110,
    damping: 28,
  });

  // TODO: add more information about me and my roles
  return (
    <section
      ref={sectionRef}
      id="home"
      className="content-wrap section-space relative flex min-h-[100svh] scroll-mt-24 items-center pt-24"
    >
      <div className="site-grid pointer-events-none absolute inset-0 z-0 opacity-10"></div>
      <motion.div
        style={{ y: parallaxY }}
        className="grid w-full items-end gap-12 lg:grid-cols-[1.2fr_0.8fr]"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.5 }}
        variants={containerVariants}
      >
        <div>
          <motion.p
            variants={itemVariants}
            className="mb-5 text-xs tracking-[0.24em] text-[var(--color-on-surface-muted)] uppercase"
          >
            <DecoderText text="Executive Portfolio" delay={1800} />
          </motion.p>

          <motion.h1
            variants={itemVariants}
            className="font-display text-5xl leading-[1.02] text-[var(--color-on-surface)] sm:text-6xl md:text-7xl"
          >
            Jared Sheohn L. Acebes
          </motion.h1>

          <motion.p
            variants={itemVariants}
            className="mt-6 font-mono text-lg tracking-tight text-[var(--color-on-surface)] md:text-xl"
          >
            <DecoderText text="wǒ cào nǐ mā" delay={2400} />
          </motion.p>

          <motion.div
            variants={itemVariants}
            className="mt-6 flex items-center gap-3"
          >
            <div className="relative flex h-3 w-3 items-center justify-center">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-500 opacity-75"></span>
              <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500"></span>
            </div>
            <span className="text-sm font-medium tracking-wide text-[var(--color-on-surface)]">
              Available for Opportunities
            </span>
          </motion.div>

          <motion.p
            variants={itemVariants}
            className="mt-4 max-w-2xl text-base leading-relaxed text-[var(--color-on-surface-muted)] md:text-lg"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </motion.p>

          <motion.div variants={itemVariants} className="mt-10">
            <motion.a
              href="#footer"
              whileHover={{ scale: 1.03, y: -2 }}
              whileTap={{ scale: 0.985 }}
              transition={{ type: 'spring', stiffness: 350, damping: 24 }}
              className="inline-flex rounded-lg bg-[radial-gradient(circle_at_top_left,var(--color-primary-container),var(--color-primary))] px-6 py-3 text-sm font-semibold tracking-wide text-slate-100 shadow-[0_18px_34px_rgba(28,28,25,0.22)]"
            >
              Initiate Strategic Engagement
            </motion.a>
          </motion.div>
        </div>

        <motion.aside
          variants={itemVariants}
          className="group relative rounded-2xl border border-[var(--color-surface-container-highest)] bg-[color-mix(in_srgb,var(--color-surface-container-high)_50%,transparent)] p-6 transition-all duration-300 hover:-translate-y-1 hover:border-[var(--color-outline-variant)] hover:shadow-[4px_4px_0_0_var(--color-surface-container-highest)] dark:hover:shadow-[4px_4px_0_0_var(--color-primary-container)]"
        >
          <p className="text-xs tracking-[0.16em] text-[var(--color-tertiary)] uppercase">
            Strategic Note
          </p>
          <p className="mt-4 text-sm leading-relaxed text-[var(--color-on-surface-muted)]">
            Dedicated to driving unhindered technical innovation. Specializing
            in highly optimized architectures and uncompromising visual
            precision.
          </p>
        </motion.aside>
      </motion.div>
    </section>
  );
}

// src/components/HeroSection.svelte
<script lang="ts">
  import { spring } from 'svelte/motion';
  import { inview } from '../lib/actions/inview';
  import { scrollState } from '../store';
  import DecoderText from './DecoderText.svelte';

  const parallaxY = spring(0, {
    stiffness: 0.11,
    damping: 0.28,
  });

  scrollState.subscribe(({ scrollY, scrollHeight, innerHeight }) => {
    if (scrollHeight > innerHeight && innerHeight > 0) {
      const scrollYProgress = scrollY / (scrollHeight - innerHeight);
      $parallaxY = scrollYProgress * -40; // Map [0, 1] to [0, -40]
    } else {
      $parallaxY = 0;
    }
  });
</script>

<section
  id="home"
  class="content-wrap section-space relative flex min-h-[100svh] scroll-mt-24 items-center pt-24 hero-section"
  use:inview={{ once: true, amount: 0.5 }}
>
  <div
    class="site-grid pointer-events-none absolute inset-0 z-0 opacity-10"
  ></div>

  <div
    style:transform="translateY({$parallaxY}px)"
    class="grid w-full items-end gap-12 lg:grid-cols-[1.2fr_0.8fr]"
  >
    <div>
      <p
        style:transition-delay="0ms"
        class="hero-item mb-5 text-xs tracking-[0.24em] text-[var(--color-on-surface-muted)] uppercase"
      >
        <DecoderText text="Executive Portfolio" delay={1800} />
      </p>

      <h1
        style:transition-delay="120ms"
        class="hero-item font-display text-5xl leading-[1.02] text-[var(--color-on-surface)] sm:text-6xl md:text-7xl"
      >
        Jared Sheohn L. Acebes
      </h1>

      <p
        style:transition-delay="240ms"
        class="hero-item mt-6 font-mono text-lg tracking-tight text-[var(--color-on-surface)] md:text-xl"
      >
        <DecoderText text="wǒ cào nǐ mā" delay={2400} />
      </p>

      <div
        style:transition-delay="360ms"
        class="hero-item mt-6 flex items-center gap-3"
      >
        <div class="relative flex h-3 w-3 items-center justify-center">
          <span
            class="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-500 opacity-75"
          ></span>
          <span class="relative inline-flex h-2 w-2 rounded-full bg-emerald-500"
          ></span>
        </div>
        <span
          class="text-sm font-medium tracking-wide text-[var(--color-on-surface)]"
        >
          Available for Opportunities
        </span>
      </div>

      <p
        style:transition-delay="480ms"
        class="hero-item mt-4 max-w-2xl text-base leading-relaxed text-[var(--color-on-surface-muted)] md:text-lg"
      >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      </p>

      <div style:transition-delay="600ms" class="hero-item mt-10">
        <a
          href="#footer"
          class="inline-flex rounded-lg bg-[radial-gradient(circle_at_top_left,var(--color-primary-container),var(--color-primary))] px-6 py-3 text-sm font-semibold tracking-wide text-slate-100 shadow-[0_18px_34px_rgba(28,28,25,0.22)] transition-transform hover:-translate-y-0.5 hover:scale-[1.03] active:scale-[0.985]"
        >
          Initiate Strategic Engagement
        </a>
      </div>
    </div>

    <aside
      style:transition-delay="720ms"
      class="hero-item group relative rounded-2xl border border-[var(--color-surface-container-highest)] bg-[color-mix(in_srgb,var(--color-surface-container-high)_50%,transparent)] p-6 transition-all duration-300 hover:-translate-y-1 hover:border-[var(--color-outline-variant)] hover:shadow-[4px_4px_0_0_var(--color-surface-container-highest)] dark:hover:shadow-[4px_4px_0_0_var(--color-primary-container)]"
    >
      <p
        class="text-xs tracking-[0.16em] text-[var(--color-tertiary)] uppercase"
      >
        Strategic Note
      </p>
      <p
        class="mt-4 text-sm leading-relaxed text-[var(--color-on-surface-muted)]"
      >
        Dedicated to driving unhindered technical innovation. Specializing in
        highly optimized architectures and uncompromising visual precision.
      </p>
    </aside>
  </div>
</section>

<style>
  .hero-item {
    opacity: 0;
    transform: translateY(18px);
    transition:
      opacity 0.7s cubic-bezier(0.22, 1, 0.36, 1),
      transform 0.7s cubic-bezier(0.22, 1, 0.36, 1);
  }

  :global(.hero-section.in-view) .hero-item {
    opacity: 1;
    transform: translateY(0);
  }
</style>
